### ISSUE TITLE
Importando planilhas Excel com Django

### ISSUE THREAD

**Issue by rg3915** [rg3915/estoque#53]

**Comment by endersonmenezes** [comment]
@rg3915 posso te ajudar com esse projeto? Como você gostaria de fazer a exportação e importação?

**Comment by rg3915** [comment]
@endersonmenezes eu já resolvi, mas se você tiver um jeito diferente...

**Comment by endersonmenezes** [comment]
O que você está usando, pode referenciar o código para eu achar mais rápido?

**Comment by rg3915** [comment]
@endersonmenezes repare que eu já fechei a issue, e tem  o link do commit [25d1b17](https://github.com/rg3915/estoque/commit/25d1b17f7380f4774109596d3d714f466e354ed9).
