### ISSUE TITLE
Filtrar Lista de Produtos na Saída para Saldo > 0

### ISSUE THREAD

**Issue by rafaelzinezi** [rg3915/estoque#61]
Régis, @rg3915 
Que tal na add de saída filtrar o dropdown de produtos para listar apenas produtos com saldo > 0 ?

**Comment by rg3915** [comment]
@rafaelzinezi aceito PR. :smile:

**Comment by rafaelzinezi** [comment]
Bora!

**Comment by rafaelzinezi** [comment]
Nunca fiz isso. Você que tem q criar um branch né?

**Comment by rafaelzinezi** [comment]
depois de várias tentativas de fazer entre view e form, sem sucesso, estou tentando no js agora
https://djangopy.org/learn/dynamically-filter-queryset-with-ajax-and-drf/

**Comment by rg3915** [comment]
Grande @rafaelzinezi resolvido. https://youtu.be/kTjN3SK3-rw
