### ISSUE TITLE
Criar tela de Consulta de entradas e saídas por data

### ISSUE THREAD

**Issue by rogeriodelphi** [rg3915/estoque#71]
Criar página que filtre as  entradas ocorridas em um determinado período. Por exemplo: todas as entradas ocorridas de 01/01/2020 até 09/08/2020.

**Comment by rogeriodelphi** [comment]
Acho que seria bastante desafiante e interessante para acompanharmos.

**Comment by rg3915** [comment]
@rogeriodelphi Acabei de lançar um video falando sobre filtro entre datas no YT https://youtu.be/sqhQM5KUFHE
E as anotações estão aqui https://github.com/rg3915/dicas-de-django#15---busca-por-data-no-frontend

**Comment by rogeriodelphi** [comment]
Ficou perfeito. Obrigado por mais uma contribuição importante para toda a comunidade.

**Comment by rogeriodelphi** [comment]
Obrigado pela implementação!
